# Generated by Django 5.2.14 on 2026-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('merchant', 'Merchant')], default='member', max_length=10),
        ),
    ]
